export const EMAIL_GET_REQUEST = 'EMAIL_GET_REQUEST';
export const EMAIL_GET_SUCCESS = 'EMAIL_GET_SUCCESS';
export const EMAIL_GET_FAIL = 'EMAIL_GET_FAIL';

export const EMAIL_POST_REQUEST = 'EMAIL_POST_REQUEST';
export const EMAIL_POST_SUCCESS = 'EMAIL_POST_SUCCESS';
export const EMAIL_POST_FAIL = 'EMAIL_POST_FAIL';